[package]
name = "smart_holmes"
version = "0.1.0"
authors = ["Peter <peter.zdankin@uni-due.de>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
rand = "*"